openapi: 3.1.0
info:
  title: Library API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local dev servers
  - url: https://library-api-88rw.onrender.com
    description: Production server on render
tags:
  - name: User
    description: User-related endpoints
  - name: Author
    description: Author-related endpoints
  - name: Book
    description: Book-related endpoints
  - name: Review
    description: Review-related endpoints
paths:
  /users:
    get:
      summary: List all users
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/users'
        '401':
          $ref: '#/components/responses/UnauthorizedRequest'
        '403':
          $ref: '#/components/responses/ForbiddenRequest'
  /users/signup:
    post:
      summary: User sign up
      tags:
        - User
      requestBody:
        description: Info to get signed up
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: TameImpala
                password:
                  type: string
                  example: didyouknowtameimpalaisoneguy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 3
                  username:
                    type: string
                    example: TameImpala
                  role:
                    type: string
                    example: member
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Username must be alphanumeric
        '401':
          $ref: '#/components/responses/UnauthorizedRequest'
        '403':
          $ref: '#/components/responses/ForbiddenRequest'
        '409':
          description: Username not unique
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Username must unique
  /users/login:
    post:
      summary: User login
      tags:
        - User
      requestBody:
        description: Info to login
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: TameImpala
                password:
                  type: string
                  example: didyouknowtameimpalaisoneguy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
        '401':
          description: Validation failed, login failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Invalid Credentials
  /users/{id}:
    put:
      summary: Update a users name and password via their user_id
      tags:
        - User
      parameters:
        - name: id
          in: path
          description: user_id
          required: true
          schema:
            type: integer
            example: 3
      requestBody:
        description: Info to change
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: BonJovi
                password:
                  type: string
                  example: BrandNewPassword
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 3
                  username:
                    type: string
                    example: BonJovi
                  role:
                    type: string
                    example: member
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Password mut be between 8 and 64 characters
        '401':
          $ref: '#/components/responses/UnauthorizedRequest'
        '403':
          $ref: '#/components/responses/ForbiddenRequest'
        '404':
          description: User Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Could not find a user with that id
        '409':
          description: Username not unique
          content:
            application/json:
              schema:
                type: object
                properties:
                  Error:
                    type: string
                    example: Username must unique
components:
  schemas:
    users:
      type: object
      properties:
        user_id:
          readOnly: true
          type: integer
          example: 1
        username:
          type: string
          example: Lady Gaga
        role:
          type: string
          enum:
            - admin
            - member
          example: member
  responses:
    UnauthorizedRequest:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              Error:
                type: string
                example: Authentication required to access this resource
    ForbiddenRequest:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              Error:
                type: string
                example: You do not have permission to access this resource
